/**
 * Storybook preset for the CSS Vars addon.
 *
 *   managerEntries     → loaded inside the manager iframe (panel UI).
 *                        Built by esbuild — does NOT see Vite virtual
 *                        modules, so we materialize the parsed token
 *                        list to `tokens.generated.ts` before registering.
 *   previewAnnotations → loaded inside the preview iframe (Vite, which
 *                        DOES resolve `virtual:weasel-tokens`).
 */
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');
const TOKENS_CSS = resolve(repoRoot, 'packages/weasel-theme/src/tokens.css');
const GENERATED = resolve(here, 'tokens.generated.ts');

interface Token {
  readonly name: string;
  readonly defaultValue: string;
  readonly group: string;
}

function parseTokens(css: string): Token[] {
  const noComments = css.replace(/\/\*[\s\S]*?\*\//g, '');
  // Only consider `:root { ... }` blocks — theme-scoped overrides
  // (`[data-theme='light']`) would otherwise clobber canonical defaults.
  const rootBodies: string[] = [];
  // `:root` must not be preceded by an identifier char (avoid e.g.
  // `--foo:root` inside a value). Body is up to the next `}`.
  const rootRe = /(?<![\w-]):root\s*\{([^}]*)\}/g;
  let rm: RegExpExecArray | null;
  while ((rm = rootRe.exec(noComments)) !== null) rootBodies.push(rm[1]);
  const source = rootBodies.length > 0 ? rootBodies.join('\n') : noComments;
  const out: Token[] = [];
  const seen = new Set<string>();
  const re = /(--wzl-[a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) {
    const name = m[1];
    const value = m[2].trim().replace(/\s+/g, ' ');
    if (seen.has(name)) {
      const idx = out.findIndex((t) => t.name === name);
      if (idx >= 0) out[idx] = { ...out[idx], defaultValue: value };
      continue;
    }
    seen.add(name);
    const tail = name.replace(/^--wzl-/, '');
    const dash = tail.indexOf('-');
    out.push({ name, defaultValue: value, group: dash === -1 ? tail : tail.slice(0, dash) });
  }
  return out;
}

function regenerate(): void {
  try {
    const css = readFileSync(TOKENS_CSS, 'utf8');
    const tokens = parseTokens(css);
    const banner = '// AUTO-GENERATED by preset.ts — do not edit.\n';
    const body = `export interface Token { readonly name: string; readonly defaultValue: string; readonly group: string }\nconst tokens: readonly Token[] = ${JSON.stringify(tokens, null, 2)};\nexport default tokens;\n`;
    if (!existsSync(dirname(GENERATED))) mkdirSync(dirname(GENERATED), { recursive: true });
    writeFileSync(GENERATED, banner + body, 'utf8');
  } catch (err) {
    // Don't take down Storybook startup over this; ship empty tokens
    // and log to console so the dev can see the issue.
    // eslint-disable-next-line no-console
    console.warn('[weasel/css-vars] failed to regenerate tokens:', err);
    writeFileSync(
      GENERATED,
      '// AUTO-GENERATED — parse failed; see startup log.\nexport interface Token { readonly name: string; readonly defaultValue: string; readonly group: string }\nconst tokens: readonly Token[] = [];\nexport default tokens;\n',
      'utf8',
    );
  }
}

// Regenerate every time the preset is evaluated (i.e. each Storybook
// start). It's a single file read + write; cost is negligible. We do
// NOT watch for changes here — manager bundles need a full restart
// anyway; the Vite plugin handles preview-side hot-reload.
regenerate();

export const managerEntries = async (entry: string[] = []): Promise<string[]> => [
  ...entry,
  resolve(here, 'manager.tsx'),
];

export const previewAnnotations = async (entry: string[] = []): Promise<string[]> => [
  ...entry,
  resolve(here, 'preview.tsx'),
];
