/**
 * Storybook preset for the CSS Vars addon.
 *
 *   managerEntries     → loaded inside the manager iframe (panel UI).
 *                        Built by esbuild, which cannot resolve the
 *                        workspace package, so we materialize the token
 *                        list to `tokens.generated.ts` before registering.
 *   previewAnnotations → loaded inside the preview iframe (Vite, which
 *                        resolves `@weasel-js/theme` to source).
 */
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { TOKEN_MANIFEST } from '../../../packages/theme/src/generated/manifest';

const here = dirname(fileURLToPath(import.meta.url));
const GENERATED = resolve(here, 'tokens.generated.ts');

interface Token {
  readonly name: string;
  readonly defaultValue: string;
  readonly group: string;
}

function regenerate(): void {
  const tokens: Token[] = TOKEN_MANIFEST.map((t) => ({
    name: t.name,
    defaultValue: t.defaultValue,
    group: t.group,
  }));
  const banner = '// AUTO-GENERATED by preset.ts — do not edit.\n';
  const body = `export interface Token { readonly name: string; readonly defaultValue: string; readonly group: string }\nconst tokens: readonly Token[] = ${JSON.stringify(tokens, null, 2)};\nexport default tokens;\n`;
  if (!existsSync(dirname(GENERATED))) mkdirSync(dirname(GENERATED), { recursive: true });
  writeFileSync(GENERATED, banner + body, 'utf8');
}

// Regenerate every time the preset is evaluated (i.e. each Storybook
// start). Manager bundles need a full restart to pick up changes anyway;
// the preview side imports the manifest directly and hot-reloads with it.
regenerate();

export const managerEntries = async (entry: string[] = []): Promise<string[]> => [
  ...entry,
  resolve(here, 'manager.tsx'),
];

export const previewAnnotations = async (entry: string[] = []): Promise<string[]> => [
  ...entry,
  resolve(here, 'preview.tsx'),
];
