// Emits src/glyphs.ts from the definitions in ./glyphs/.
//
// The definitions compute their own geometry, so the checked-in glyphs.ts holds
// resolved literals and ships no math. Re-run after touching anything here:
//
//   npm run gen:cursors
//
// Proof a change before committing it:
//
//   node packages/cursor/scripts/proof-cursors.mjs

import { writeFileSync } from 'node:fs';
import { DRAW } from './glyphs/draw.mjs';
import { SHAPES } from './glyphs/shapes.mjs';
import { TRANSFORM } from './glyphs/transform.mjs';

const ALL = { ...DRAW, ...SHAPES, ...TRANSFORM };

const out = `// GENERATED by scripts/gen-cursors.mjs — do not edit by hand.
// Filled silhouettes on a 24-unit box; the halo is applied at bake time.

import type { CursorGlyph } from './types';

export const GLYPHS = ${JSON.stringify(ALL, null, 2)} as const satisfies Record<string, CursorGlyph>;

/** Every glyph name in the set. */
export type CursorGlyphName = keyof typeof GLYPHS;
`;

writeFileSync(new URL('../src/glyphs.ts', import.meta.url), out);
console.log(`wrote ${Object.keys(ALL).length} glyphs to src/glyphs.ts`);
