import { fullSelection, pickAll, type AxisDefs, type Selection } from '../../axes';
import { resolveTokens } from '../../dtcg/resolve';
import type { RawToken } from '../../dtcg/types';
import type { BakedTheme } from '../bake';
import type { AxisDependency } from '../deps';

export interface EmitInput {
  readonly baked: BakedTheme;
  readonly deps: Readonly<Record<string, AxisDependency>>;
  /** The default theme alone gets `:root` and the unscoped selectors. */
  readonly isDefault: boolean;
}

const REF = /^\{([^}]+)\}$/;

/** `{gray-100}` → `gray-100`. A group prefix (`{color.gray-100}`) is dropped, as `resolveTokens` does. */
function refTarget(token: RawToken): string | null {
  const m = typeof token.value === 'string' ? REF.exec(token.value.trim()) : null;
  if (!m) return null;
  const path = m[1];
  const dot = path.indexOf('.');
  return dot === -1 ? path : path.slice(dot + 1);
}

/** A reference becomes `var()` (or `color-mix()` with an alpha); a literal is resolved. */
export function cssValue(name: string, token: RawToken): string {
  const target = refTarget(token);
  if (target === null) return resolveTokens({ [name]: token })[name];
  if (token.alpha === undefined) return `var(--wzl-${target})`;
  return `color-mix(in srgb, var(--wzl-${target}) ${Math.round(token.alpha * 100)}%, transparent)`;
}

/** Non-empty subsets of the axes, in declaration order, smallest first. */
function axisSets(axes: AxisDefs): string[][] {
  const names = Object.keys(axes);
  const sets: string[][] = [];
  for (let mask = 1; mask < 1 << names.length; mask += 1) sets.push(names.filter((_, i) => mask & (1 << i)));
  return sets.sort((a, b) => a.length - b.length);
}

function combinations(axes: AxisDefs, set: readonly string[]): Selection[] {
  let out: Record<string, string>[] = [{}];
  for (const axis of set) out = out.flatMap((s) => Object.keys(axes[axis].values).map((v) => ({ ...s, [axis]: v })));
  return out;
}

export function emitCss(themes: readonly EmitInput[]): string {
  const lines = [
    '/* GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    ' * Source: packages/theme/themes/<theme>.json',
    ' */',
    '',
  ];

  for (const { baked, deps, isDefault } of themes) {
    const { axes, name: theme } = baked;
    const order = Object.keys(baked.tokens);
    const axesOf = (name: string) => (deps[name]?.all ?? []).join(',');

    if (isDefault) {
      const defaults = pickAll(baked.tokens, fullSelection(axes, {}));
      // The default selection's scheme, not just its values: a surface that never calls
      // applyTheme would otherwise get dark colors with light native widgets.
      lines.push(':root {');
      for (const def of Object.values(axes)) {
        const scheme = def.values[def.default]?.scheme;
        if (scheme) lines.push(`  color-scheme: ${scheme};`);
      }
      for (const [name, token] of Object.entries(defaults)) {
        if (token.description) lines.push(`  /* ${token.description} */`);
        lines.push(`  --wzl-${name}: ${cssValue(name, token)};`);
      }
      lines.push('}', '');
    } else {
      const invariant = order.filter((n) => axesOf(n) === '');
      if (invariant.length > 0) {
        const values = pickAll(baked.tokens, fullSelection(axes, {}));
        lines.push(`[data-wzl-theme='${theme}'] {`);
        for (const name of invariant) if (values[name]) lines.push(`  --wzl-${name}: ${cssValue(name, values[name])};`);
        lines.push('}', '');
      }
    }

    for (const set of axisSets(axes)) {
      const members = order.filter((n) => axesOf(n) === set.join(','));
      const hasOwn = (n: string) => (deps[n]?.own.length ?? 0) > 0;
      const ownFirst = [...members.filter(hasOwn), ...members.filter((n) => !hasOwn(n))];
      const schemeAxis = set.length === 1 ? set[0] : undefined;

      for (const combo of combinations(axes, set)) {
        const scheme = schemeAxis ? axes[schemeAxis].values[combo[schemeAxis]]?.scheme : undefined;
        if (ownFirst.length === 0 && !scheme) continue;
        const attrs = set.map((a) => `[data-wzl-${a}='${combo[a]}']`).join('');
        if (isDefault) lines.push(`[data-wzl-theme='${theme}']${attrs},`, `${attrs} {`);
        else lines.push(`[data-wzl-theme='${theme}']${attrs} {`);
        if (scheme) lines.push(`  color-scheme: ${scheme};`);
        const values = pickAll(baked.tokens, fullSelection(axes, combo));
        for (const name of ownFirst) if (values[name]) lines.push(`  --wzl-${name}: ${cssValue(name, values[name])};`);
        lines.push('}', '');
      }
    }
  }

  return lines.join('\n');
}
