import { fullSelection, pickAll } from '../../axes';
import { resolveTokens } from '../../dtcg/resolve';
import type { EmitInput } from './css';

export function emitManifest({ baked }: EmitInput): string {
  const all = pickAll(baked.tokens, fullSelection(baked.axes, {}));
  const resolved = resolveTokens(all);
  const rows = Object.entries(all).map(([name, token]) => {
    const group = name.includes('-') ? name.slice(0, name.indexOf('-')) : name;
    return `  { name: '--wzl-${name}', type: ${JSON.stringify(token.type)}, group: ${JSON.stringify(group)}, defaultValue: ${JSON.stringify(resolved[name])}, description: ${JSON.stringify(token.description ?? '')} },`;
  });
  return [
    '// GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    '',
    '/** One row of `TOKEN_MANIFEST`: a token, its DTCG type, the name-prefix',
    ' *  group it belongs to, its value in the default theme and selection, and',
    ' *  the description it was authored with (empty string if none). */',
    'export interface TokenManifestEntry {',
    '  readonly name: string;',
    '  readonly type: string;',
    '  readonly group: string;',
    '  readonly defaultValue: string;',
    '  readonly description: string;',
    '}',
    '',
    '/** Every token of the default theme at its default selection, described.',
    ' *  Meant for tooling that presents the token set — docs pages, token',
    ' *  browsers, the Storybook CSS-vars addon — not for resolving values at',
    ' *  runtime. */',
    'export const TOKEN_MANIFEST: readonly TokenManifestEntry[] = [',
    rows.join('\n'),
    '];',
    '',
  ].join('\n');
}
