import { fullSelection, pickAll } from '../../axes';
import { resolveTokens } from '../../dtcg/resolve';
import { TOKEN_HOOKS } from '../../hooks';
import type { EmitInput } from './css';

const groupOf = (name: string) => (name.includes('-') ? name.slice(0, name.indexOf('-')) : name);

const row = (
  name: string,
  type: string,
  value: string,
  description: string,
  hook: boolean,
): string =>
  `  { name: '--wzl-${name}', type: ${JSON.stringify(type)}, group: ${JSON.stringify(groupOf(name))}, defaultValue: ${JSON.stringify(value)}, description: ${JSON.stringify(description)}, hook: ${hook} },`;

export function emitManifest({ baked }: EmitInput): string {
  const all = pickAll(baked.tokens, fullSelection(baked.axes, {}));
  const resolved = resolveTokens(all);
  const rows = Object.entries(all).map(([name, token]) =>
    row(name, token.type, resolved[name], token.description ?? '', false),
  );
  // Hooks last, and sorted, so a name moving between the two lists is one
  // block of diff rather than a reshuffle.
  for (const h of [...TOKEN_HOOKS].sort((a, b) => a.name.localeCompare(b.name))) {
    rows.push(row(h.name, h.type, h.value, h.description, true));
  }
  return [
    '// GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    '',
    '/** One row of `TOKEN_MANIFEST`: a token, its DTCG type, the name-prefix',
    ' *  group it belongs to, its value in the default theme and selection, and',
    ' *  the description it was authored with (empty string if none). */',
    'export interface TokenManifestEntry {',
    '  readonly name: string;',
    '  readonly type: string;',
    '  readonly group: string;',
    '  readonly defaultValue: string;',
    '  readonly description: string;',
    '  /** A consumer override hook rather than a theme token: no theme declares',
    '   *  it, kit CSS reads it with `defaultValue` as the fallback, and setting',
    '   *  it on any container is what changes it. */',
    '  readonly hook: boolean;',
    '}',
    '',
    '/** Every token of the default theme at its default selection, plus every',
    ' *  consumer override hook, described. Meant for tooling that presents the',
    ' *  token set — docs pages, token browsers, forge\'s CSS-vars panel — not',
    ' *  for resolving values at runtime. */',
    'export const TOKEN_MANIFEST: readonly TokenManifestEntry[] = [',
    rows.join('\n'),
    '];',
    '',
  ].join('\n');
}
