import { enumerateSelections, pickAll, selectionKey, type Selection } from '../../axes.ts';
import type { ThemeDefinition } from '../../definition.ts';
import { resolveTokens } from '../../dtcg/resolve.ts';
import type { FlatTokens } from '../../dtcg/types.ts';
import type { BakedTheme } from '../bake.ts';

export interface ThemesInput {
  readonly definition: ThemeDefinition;
  readonly baked: BakedTheme;
}

/** `baked` and every theme above it, root first. */
function chainOf(baked: BakedTheme, byName: ReadonlyMap<string, BakedTheme>): BakedTheme[] {
  const parent = baked.extends ? byName.get(baked.extends) : undefined;
  if (baked.extends && !parent) throw new Error(`Theme "${baked.name}" extends "${baked.extends}", which is not in themes/`);
  return [...(parent ? chainOf(parent, byName) : []), baked];
}

/** Each token from the nearest theme in the chain that has it at `sel`, as `resolveTheme` merges them. */
function tokensAt(chain: readonly BakedTheme[], sel: Selection): FlatTokens {
  return Object.assign({}, ...chain.map((t) => pickAll(t.tokens, sel)));
}

export function emitThemes(themes: readonly ThemesInput[]): string {
  const byName = new Map(themes.map((t) => [t.baked.name, t.baked]));
  const names = new Set<string>();

  const entries = themes.map(({ baked }) => {
    const chain = chainOf(baked, byName);
    const selections = enumerateSelections(baked.axes).map((sel) => {
      const resolved = resolveTokens(tokensAt(chain, sel));
      for (const n of Object.keys(resolved)) names.add(`--wzl-${n}`);
      const body = Object.entries(resolved).map(([n, v]) => `        '--wzl-${n}': ${JSON.stringify(v)},`).join('\n');
      return `      '${selectionKey(baked.axes, sel)}': {\n${body}\n      },`;
    });
    return [
      `  ${JSON.stringify(baked.name)}: {`,
      `    name: ${JSON.stringify(baked.name)},`,
      `    axes: ${JSON.stringify(baked.axes)},`,
      '    selections: {',
      selections.join('\n'),
      '    },',
      '  },',
    ].join('\n');
  });

  const sources = Object.fromEntries(themes.map((t) => [t.definition.name, t.definition]));
  const bakedAll = Object.fromEntries(themes.map((t) => [t.baked.name, t.baked]));

  return [
    '// GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    '',
    "import type { AxisDefs } from '../axes.ts';",
    "import type { ThemeDefinition } from '../definition.ts';",
    "import type { BakedTheme } from '../engine/bake.ts';",
    '',
    '/** Every design token the built-in themes declare, spelled as the CSS',
    ' *  custom property it becomes. */',
    'export type TokenName =',
    `${[...names].sort().map((n) => `  | '${n}'`).join('\n')};`,
    '',
    '/** A built-in theme with its aliases already collapsed: every selection',
    ' *  (keyed `mode=dark`, axes in declaration order) maps every token name to',
    ' *  a final CSS value. */',
    'export interface GeneratedTheme {',
    '  readonly name: string;',
    '  readonly axes: AxisDefs;',
    '  readonly selections: Readonly<Record<string, Readonly<Record<TokenName, string>>>>;',
    '}',
    '',
    '/** The built-in themes, resolved, keyed by theme name. Read this to list',
    ' *  or preview themes without resolving a token graph yourself. */',
    'export const THEMES = {',
    entries.join('\n'),
    '} as const satisfies Record<string, GeneratedTheme>;',
    '',
    '/** The built-in themes as authored: their unbaked definitions. */',
    `export const THEME_SOURCES: Readonly<Record<string, ThemeDefinition>> = ${JSON.stringify(sources, null, 2)};`,
    '',
    '/** The built-in themes with every rule run and references intact. This is',
    ' *  what `weaselTheme` is built from, so the runtime entry bundles no generator. */',
    `export const BAKED_THEMES: Readonly<Record<string, BakedTheme>> = ${JSON.stringify(bakedAll, null, 2)};`,
    '',
  ].join('\n');
}
