// Emits src/icons/paths.ts from the glyph definitions in ./icons/.
//
// The definitions compute their own terminus geometry (see icons/base.mjs), so
// the checked-in paths.ts holds resolved literals and ships no math. Re-run
// after touching anything under scripts/icons/:
//
//   node packages/ui/scripts/gen-icons.mjs
//
// Proof a change before committing it — CLAUDE.md ("Drawing icons") requires
// inspecting at 240-320px, not at chrome size.

import { writeFileSync } from 'node:fs';
import { BASE } from './icons/base.mjs';
import { ACTIONS } from './icons/actions.mjs';
import { INSTRUMENT, PLAYBACK, STATUS } from './icons/state.mjs';
import { PAINT } from './icons/paint.mjs';
import { LAYOUT } from './icons/layout.mjs';
import { ARCS } from './icons/arcs.mjs';
import { CURVES } from './icons/curves.mjs';
import { SHAPES } from './icons/shapes.mjs';
import { SOLIDS } from './icons/solids.mjs';

// `save` split: the tray-and-arrow reads as download, so it carries `export`,
// and capturing a trial's state gets its own camera.
const RENAME = { save: 'export', zoom: 'zoomIn' };

const GROUPS = [
  ['View and lifecycle', BASE],
  ['Actions', ACTIONS],
  ['Playback', PLAYBACK],
  ['State', STATUS],
  ['Instrument', INSTRUMENT],
  ['Stroke cap, join, align and dash', PAINT],
  ['Workspace layout', LAYOUT],
  ['Arc profiles', ARCS],
  ['Curves', CURVES],
  ['Shapes', SHAPES],
  ['Platonic solids', SOLIDS],
];

// A digit has no upper case, so `star-4` has to drop the dash rather than try to
// capitalize it — an emitted `shapeStar-4` is not a valid object key.
const camel = (k) => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
// Join with a space (attributes split across lines must stay separated),
// then close the gaps between adjacent elements.
const clean = (body) =>
  body
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join(' ')
    .replace(/>\s+</g, '><');

// A name collision used to be skipped in silence, so a new glyph could vanish
// into an existing one's key with the generator reporting success. Identical
// bodies are the deliberate alias (`export` is `BASE.save`); different ones are
// someone's drawing being dropped.
// A drawn glyph arrives as a string of markup; a plotted one arrives as
// { d, width, inner, fill, rule, join } and is turned into markup here, so the definitions stay
// geometry and the emitter stays the only place that writes elements.
const element = (glyph) =>
  typeof glyph === 'string'
    ? clean(glyph)
    : `<path d="${glyph.d}"${glyph.join ? ` stroke-linejoin="${glyph.join}"` : ''}` +
      `${glyph.width ? ` stroke-width="${glyph.width}"` : ''}/>` +
      (glyph.inner ? `<path d="${glyph.inner.d}" stroke-width="${glyph.inner.width}"/>` : '');
const fillElement = (glyph) =>
  typeof glyph === 'string' || !glyph.fill
    ? null
    : `<path d="${glyph.fill}" fill="currentColor" stroke="none"` +
      `${glyph.rule ? ` fill-rule="${glyph.rule}"` : ''}/>`;

const seen = new Map();
const fills = new Map();
const members = [];
let out = `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Every glyph is a 20x20 viewBox drawn in currentColor at stroke-width 1.5.

export const ICON_PATHS = {
`;

for (const [label, set] of GROUPS) {
  out += `\n  // ${label}\n`;
  const names = [];
  members.push([label, names]);
  for (const [rawKey, body] of Object.entries(set)) {
    if (rawKey.startsWith('_') || rawKey === 'attrs') continue;
    const key = camel(RENAME[rawKey] ?? rawKey);
    const drawing = element(body);
    const prior = seen.get(key);
    if (prior !== undefined) {
      if (prior === drawing) continue;
      throw new Error(`icon "${key}" is drawn twice, differently — rename one`);
    }
    seen.set(key, drawing);
    names.push(key);
    const fill = fillElement(body);
    if (fill) fills.set(key, fill);
    out += `  ${key}: \`${drawing}\`,\n`;
  }
}

out += `} as const;

/** Every glyph name in the set. */
export type IconName = keyof typeof ICON_PATHS;

/** The region a glyph encloses, for \`<Icon filled>\`. A shape fills its own
 *  outline; a plotted curve fills down to the frame's baseline, reaching the outer
 *  edge of the stroke rather than stopping at the path's own endpoint. Only the
 *  glyphs where an enclosed region means something have an entry. */
export const ICON_FILLS = {
`;
for (const [key, fill] of fills) out += `  ${key}: \`${fill}\`,\n`;
out += `} as const;

/** The glyphs \`<Icon filled>\` can shade. */
export type FillableIconName = keyof typeof ICON_FILLS;

/** Every glyph in \`ICON_PATHS\`, once, sorted into the families it was drawn in. */
export const ICON_GROUPS: readonly { label: string; names: readonly IconName[] }[] = [
`;
for (const [label, names] of members) {
  out += `  {\n    label: '${label}',\n    names: [\n${names.map((n) => `      '${n}',\n`).join('')}    ],\n  },\n`;
}
out += `];
`;

writeFileSync(new URL('../src/icons/paths.ts', import.meta.url), out);
console.log(`wrote ${seen.size} glyphs (${fills.size} fillable) to src/icons/paths.ts`);
