// Emits src/icons/paths.ts from the glyph definitions in ./icons/.
//
// The definitions compute their own terminus geometry (see icons/base.mjs), so
// the checked-in paths.ts holds resolved literals and ships no math. Re-run
// after touching anything under scripts/icons/:
//
//   node packages/ui/scripts/gen-icons.mjs
//
// Proof a change before committing it — CLAUDE.md ("Drawing icons") requires
// inspecting at 240-320px, not at chrome size.

import { writeFileSync } from 'node:fs';
import { BASE } from './icons/base.mjs';
import { ACTIONS } from './icons/actions.mjs';
import { STATE } from './icons/state.mjs';

// `save` split: the tray-and-arrow reads as download, so it carries `export`,
// and capturing a trial's state gets its own camera.
const RENAME = { save: 'export', zoom: 'zoomIn' };

const GROUPS = [
  ['View and lifecycle', BASE],
  ['Actions', ACTIONS],
  ['State and instrument', STATE],
];

const camel = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
// Join with a space (attributes split across lines must stay separated),
// then close the gaps between adjacent elements.
const clean = (body) =>
  body
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join(' ')
    .replace(/>\s+</g, '><');

const seen = new Set();
let out = `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Every glyph is a 20x20 viewBox drawn in currentColor at stroke-width 1.5.

export const ICON_PATHS = {
`;

for (const [label, set] of GROUPS) {
  out += `\n  // ${label}\n`;
  for (const [rawKey, body] of Object.entries(set)) {
    if (rawKey.startsWith('_') || rawKey === 'attrs') continue;
    const key = camel(RENAME[rawKey] ?? rawKey);
    if (seen.has(key)) continue;
    seen.add(key);
    out += `  ${key}: \`${clean(body)}\`,\n`;
  }
}

out += `} as const;

/** Every glyph name in the set. */
export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(new URL('../src/icons/paths.ts', import.meta.url), out);
console.log(`wrote ${seen.size} glyphs to src/icons/paths.ts`);
