// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Every glyph is a 20x20 viewBox drawn in currentColor at stroke-width 1.5.

export const ICON_PATHS = {

  // View and lifecycle
  clone: `<path d="M7 7.4V4.6A1.6 1.6 0 0 1 8.6 3h6.8A1.6 1.6 0 0 1 17 4.6v6.8a1.6 1.6 0 0 1-1.6 1.6H12.6" stroke-linecap="butt"/><rect x="3" y="7" width="10" height="10" rx="1.6"/><path d="M5.7 10.8h4.6M5.7 13.4h3" stroke-width="1"/>`,
  reset: `<path d="M7.28 4.88A5.8 5.8 0 1 0 12.72 4.88"/><path d="M13.81 7.57 12.72 4.88 15.56 4.28"/>`,
  close: `<path d="M5 5 15 15M15 5 5 15" stroke-width="1.75"/>`,
  export: `<path d="M4 12.6v2.9A1.5 1.5 0 0 0 5.5 17h9a1.5 1.5 0 0 0 1.5-1.5v-2.9"/><path d="M10 3.2v8.5"/><path d="M11.7 9.35 10 11.7 8.3 9.35"/><path d="M6.8 14.7h6.4" stroke-width="1"/>`,
  zoomIn: `<circle cx="9" cy="9" r="5.4"/><path d="M12.82 12.82 16.9 16.9"/><path d="M9 6.7v4.6M6.7 9h4.6"/>`,
  pan: `<path d="M10 8.1V3.2M10 11.9V16.8M8.1 10H3.2M11.9 10H16.8"/><path d="M8.26 5.27 10 3.2 11.74 5.27M11.74 14.73 10 16.8 8.26 14.73M5.27 11.74 3.2 10 5.27 8.26M14.73 8.26 16.8 10 14.73 11.74"/><circle cx="10" cy="10" r="1.9"/>`,

  // Actions
  add: `<path d="M10 4.9v10.2M4.9 10h10.2"/>`,
  remove: `<path d="M4.9 10h10.2"/>`,
  delete: `<path d="M3.6 5.8h12.8M8 5.8V4.5A1.1 1.1 0 0 1 9.1 3.4h1.8A1.1 1.1 0 0 1 12 4.5v1.3"/><path d="M5.2 5.8v9.6A1.6 1.6 0 0 0 6.8 17h6.4a1.6 1.6 0 0 0 1.6-1.6V5.8"/><path d="M8.4 8.8v5.2M11.6 8.8v5.2" stroke-width="1"/>`,
  sort: `<path d="M3.6 5.6h7.2M3.6 10h8.8M3.6 14.4h5"/><path d="M15.3 5.4v9.4"/><path d="M16.97 12.81 15.3 14.8 13.63 12.81"/>`,
  undo: `<path d="M4.4 8.4h6.8a3.6 3.6 0 0 1 0 7.2H8.6"/><path d="M6.47 10.14 4.4 8.4 6.47 6.66"/>`,
  redo: `<path d="M15.6 8.4H8.8a3.6 3.6 0 0 0 0 7.2H11.4"/><path d="M13.53 6.66 15.6 8.4 13.53 10.14"/>`,
  zoomOut: `<circle cx="9" cy="9" r="5.4"/><path d="M12.82 12.82 16.9 16.9"/><path d="M6.7 9h4.6"/>`,
  fit: `<path d="M3.2 7.2V4.4A1.2 1.2 0 0 1 4.4 3.2h2.8M12.8 3.2h2.8A1.2 1.2 0 0 1 16.8 4.4v2.8M16.8 12.8v2.8a1.2 1.2 0 0 1-1.2 1.2h-2.8M7.2 16.8H4.4a1.2 1.2 0 0 1-1.2-1.2v-2.8"/><rect x="7.4" y="8.2" width="5.2" height="3.6" rx="0.8" stroke-width="1"/>`,
  snapshot: `<path d="M3.8 8.3A1.4 1.4 0 0 1 5.2 6.9h1.9L8 5.1h4l.9 1.8h1.9A1.4 1.4 0 0 1 16.2 8.3v6A1.4 1.4 0 0 1 14.8 15.7H5.2A1.4 1.4 0 0 1 3.8 14.3z"/><circle cx="10" cy="11" r="2.75"/>`,

  // State and instrument
  play: `<path d="M7.6 5.2 15.6 10 7.6 14.8Z"/>`,
  pause: `<path d="M7.8 5.2v9.6M12.2 5.2v9.6"/>`,
  stop: `<rect x="5.6" y="5.6" width="8.8" height="8.8" rx="1.4"/>`,
  step: `<path d="M6.4 5.4 13 10 6.4 14.6Z"/><path d="M15.2 5.4v9.2"/>`,
  crosshair: `<circle cx="10" cy="10" r="5.6"/><path d="M10 2.8v4.4M10 12.8v4.4M2.8 10h4.4M12.8 10h4.4"/>`,
  fullscreen: `<path d="M11.6 3.6h4.8v4.8M8.4 16.4H3.6v-4.8"/><path d="M16.4 3.6 11.2 8.8M3.6 16.4 8.8 11.2"/>`,
  compare: `<rect x="3.4" y="4.6" width="13.2" height="10.8" rx="1.6"/><path d="M10 4.6v10.8" stroke-width="1"/><path d="M5.2 7.6h3.4M5.2 10h2.6M5.2 12.4h3.4" stroke-width="1"/><path d="M11.4 7.6h3.4M11.4 10h3.4M11.4 12.4h1.8" stroke-width="1"/>`,
  filter: `<path d="M3.4 4.6h13.2L11.8 11v5.4L8.2 14.8V11z"/>`,
  search: `<circle cx="9" cy="9" r="5.4"/><path d="M12.82 12.82 16.9 16.9"/>`,
  layers: `<path d="M10 2.8 17.2 6.6 10 10.4 2.8 6.6z"/><path d="M2.8 10 10 13.8 17.2 10" stroke-width="1"/><path d="M2.8 13.4 10 17.2 17.2 13.4" stroke-width="1"/>`,
  lock: `<rect x="4.6" y="9" width="10.8" height="8" rx="1.6"/><path d="M7.2 9V6.6a2.8 2.8 0 0 1 5.6 0V9"/>`,
  unlock: `<rect x="4.6" y="9" width="10.8" height="8" rx="1.6"/><path d="M7.2 9V6.6a2.8 2.8 0 0 1 5.6 0"/>`,
  visible: `<path d="M2.6 10C4.6 6.6 7.1 5 10 5s5.4 1.6 7.4 5c-2 3.4-4.5 5-7.4 5s-5.4-1.6-7.4-5z"/><circle cx="10" cy="10" r="2.2"/>`,
  hidden: `<path d="M2.6 10C4.6 6.6 7.1 5 10 5s5.4 1.6 7.4 5c-2 3.4-4.5 5-7.4 5s-5.4-1.6-7.4-5z"/><circle cx="10" cy="10" r="2.2"/><path d="M4.2 15.8 15.8 4.2"/>`,
  pin: `<path d="M8.2 3.4v5.2l-2 2.6h7.6l-2-2.6V3.4z"/><path d="M7 3.4h6"/><path d="M10 11.2v5.4"/>`,
  link: `<path d="M8.6 11.4a3.4 3.4 0 0 1 0-4.8l2.2-2.2a3.4 3.4 0 0 1 4.8 4.8l-1.1 1.1"/><path d="M11.4 8.6a3.4 3.4 0 0 1 0 4.8l-2.2 2.2a3.4 3.4 0 0 1-4.8-4.8l1.1-1.1"/>`,
  collapse: `<path d="M14.16 4.05 10 7.8 5.84 4.05M5.84 15.95 10 12.2 14.16 15.95"/>`,
  expand: `<path d="M5.84 8.15 10 4.4 14.16 8.15M14.16 11.85 10 15.6 5.84 11.85"/>`,
  tune: `<path d="M3.4 6h13.2M3.4 10h13.2M3.4 14h13.2" stroke-width="1.25"/><circle cx="7" cy="6" r="1.8"/><circle cx="12.6" cy="10" r="1.8"/><circle cx="9" cy="14" r="1.8"/>`,
  grid: `<rect x="3.4" y="3.4" width="13.2" height="13.2" rx="1.4"/><path d="M7.8 3.4v13.2M12.2 3.4v13.2M3.4 7.8h13.2M3.4 12.2h13.2" stroke-width="1"/>`,
  snap: `<path d="M5.4 15.6V9.4a4.6 4.6 0 0 1 9.2 0v6.2h-3.2V9.4a1.4 1.4 0 0 0-2.8 0v6.2z"/><path d="M5.4 12.8h3.2M11.4 12.8h3.2" stroke-width="1"/>`,
  measure: `<rect x="2.6" y="7.4" width="14.8" height="5.2" rx="1.2"/><path d="M6 7.4v2.2M9.4 7.4v3M12.8 7.4v2.2" stroke-width="1"/>`,
  randomize: `<rect x="3.6" y="3.6" width="12.8" height="12.8" rx="2"/><circle cx="7.2" cy="7.2" r="1" fill="currentColor" stroke="none"/><circle cx="10" cy="10" r="1" fill="currentColor" stroke="none"/><circle cx="12.8" cy="12.8" r="1" fill="currentColor" stroke="none"/>`,
  refresh: `<path d="M4.27 12.09A6.1 6.1 0 0 1 14.67 6.08"/><path d="M14.67 3.38 14.67 6.08 12.01 5.61"/><path d="M15.73 7.91A6.1 6.1 0 0 1 5.33 13.92"/><path d="M5.33 16.62 5.33 13.92 7.99 14.39"/>`,
  info: `<circle cx="10" cy="10" r="7"/><path d="M10 9.4v4.4"/><path d="M10 6.5h0"/>`,
  warning: `<path d="M10 3.4 17.4 16.2H2.6z"/><path d="M10 8.4v3.4"/><path d="M10 14h0"/>`,
  error: `<circle cx="10" cy="10" r="7"/><path d="M7.6 7.6 12.4 12.4M12.4 7.6 7.6 12.4"/>`,
  busy: `<path d="M10 3.2A6.8 6.8 0 1 1 3.2 10"/>`,

  // Stroke cap, join and align
  strokeWidth: `<path d="M3.4 5.6h13.2" stroke-width="1"/><path d="M3.4 10h13.2" stroke-width="2"/><path d="M3.4 15.2h13.2" stroke-width="3.4"/>`,
  strokeCap: `<path d="M2.5 10H12" stroke-linecap="butt"/><path d="M12 6V14" stroke-width="1"/>`,
  strokeJoin: `<path d="M4.4 15.5 10 5.5 15.6 15.5" stroke-linecap="butt" stroke-linejoin="miter"/>`,
  strokeAlign: `<circle cx="10" cy="10" r="6.2"/>`,
  capButt: `<path d="M-2 10H6.7" stroke="currentColor" stroke-width="9.5" stroke-linecap="butt" stroke-linejoin="miter"/><path d="M6.7 2.4V17.6" stroke="currentColor" stroke-width="1" stroke-linecap="butt"/>`,
  capRound: `<path d="M-2 10H6.7" stroke="currentColor" stroke-width="9.5" stroke-linecap="round" stroke-linejoin="miter"/><path d="M6.7 2.4V17.6" stroke="currentColor" stroke-width="1" stroke-linecap="butt"/>`,
  capSquare: `<path d="M-2 10H6.7" stroke="currentColor" stroke-width="9.5" stroke-linecap="square" stroke-linejoin="miter"/><path d="M6.7 2.4V17.6" stroke="currentColor" stroke-width="1" stroke-linecap="butt"/>`,
  joinMiter: `<path d="M10 3.5 15.6 15.5H4.4Z" fill="currentColor" stroke="none"/>`,
  joinRound: `<path d="M4.4 15.5V12a5.6 5.6 0 0 1 11.2 0v3.5Z" fill="currentColor" stroke="none"/>`,
  joinBevel: `<path d="M6.8 8.2h6.4l2.4 7.3H4.4Z" fill="currentColor" stroke="none"/>`,
  alignInner: `<path d="M10 3.8A6.2 6.2 0 1 0 10 16.2A6.2 6.2 0 1 0 10 3.8Z" fill="currentColor" stroke="none"/>`,
  alignCenter: `<path d="M10 2.1A7.9 7.9 0 1 0 10 17.9A7.9 7.9 0 1 0 10 2.1ZM10 5.5A4.5 4.5 0 1 0 10 14.5A4.5 4.5 0 1 0 10 5.5Z" fill="currentColor" stroke="none" fill-rule="evenodd"/>`,
  alignOuter: `<path d="M0 0H20V20H0ZM10 3.8A6.2 6.2 0 1 0 10 16.2A6.2 6.2 0 1 0 10 3.8Z" fill="currentColor" stroke="none" fill-rule="evenodd"/>`,
} as const;

/** Every glyph name in the set. */
export type IconName = keyof typeof ICON_PATHS;
