// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Every glyph is a 20x20 viewBox drawn in currentColor at stroke-width 1.5.

export const ICON_PATHS = {

  // View and lifecycle
  clone: `<path d="M7 7.4V4.6A1.6 1.6 0 0 1 8.6 3h6.8A1.6 1.6 0 0 1 17 4.6v6.8a1.6 1.6 0 0 1-1.6 1.6H12.6" stroke-linecap="butt"/><rect x="3" y="7" width="10" height="10" rx="1.6"/><path d="M5.7 10.8h4.6M5.7 13.4h3" stroke-width="1"/>`,
  reset: `<path d="M7.28 4.88A5.8 5.8 0 1 0 12.72 4.88"/><path d="M13.81 7.57 12.72 4.88 15.56 4.28"/>`,
  close: `<path d="M5 5 15 15M15 5 5 15" stroke-width="1.75"/>`,
  export: `<path d="M4 12.6v2.9A1.5 1.5 0 0 0 5.5 17h9a1.5 1.5 0 0 0 1.5-1.5v-2.9"/><path d="M10 3.2v8.5"/><path d="M11.7 9.35 10 11.7 8.3 9.35"/><path d="M6.8 14.7h6.4" stroke-width="1"/>`,
  zoomIn: `<circle cx="9" cy="9" r="5.4"/><path d="M12.82 12.82 16.9 16.9"/><path d="M9 6.7v4.6M6.7 9h4.6"/>`,
  pan: `<path d="M10 8.1V3.2M10 11.9V16.8M8.1 10H3.2M11.9 10H16.8"/><path d="M8.26 5.27 10 3.2 11.74 5.27M11.74 14.73 10 16.8 8.26 14.73M5.27 11.74 3.2 10 5.27 8.26M14.73 8.26 16.8 10 14.73 11.74"/><circle cx="10" cy="10" r="1.9"/>`,

  // Actions
  add: `<path d="M10 4.9v10.2M4.9 10h10.2"/>`,
  remove: `<path d="M4.9 10h10.2"/>`,
  delete: `<path d="M3.6 5.8h12.8M8 5.8V4.5A1.1 1.1 0 0 1 9.1 3.4h1.8A1.1 1.1 0 0 1 12 4.5v1.3"/><path d="M5.2 5.8v9.6A1.6 1.6 0 0 0 6.8 17h6.4a1.6 1.6 0 0 0 1.6-1.6V5.8"/><path d="M8.4 8.8v5.2M11.6 8.8v5.2" stroke-width="1"/>`,
  sort: `<path d="M3.6 5.6h7.2M3.6 10h8.8M3.6 14.4h5"/><path d="M15.3 5.4v9.4"/><path d="M16.97 12.81 15.3 14.8 13.63 12.81"/>`,
  undo: `<path d="M4.4 8.4h6.8a3.6 3.6 0 0 1 0 7.2H8.6"/><path d="M6.47 10.14 4.4 8.4 6.47 6.66"/>`,
  redo: `<path d="M15.6 8.4H8.8a3.6 3.6 0 0 0 0 7.2H11.4"/><path d="M13.53 6.66 15.6 8.4 13.53 10.14"/>`,
  zoomOut: `<circle cx="9" cy="9" r="5.4"/><path d="M12.82 12.82 16.9 16.9"/><path d="M6.7 9h4.6"/>`,
  fit: `<path d="M3.2 7.2V4.4A1.2 1.2 0 0 1 4.4 3.2h2.8M12.8 3.2h2.8A1.2 1.2 0 0 1 16.8 4.4v2.8M16.8 12.8v2.8a1.2 1.2 0 0 1-1.2 1.2h-2.8M7.2 16.8H4.4a1.2 1.2 0 0 1-1.2-1.2v-2.8"/><rect x="7.4" y="8.2" width="5.2" height="3.6" rx="0.8" stroke-width="1"/>`,
  snapshot: `<path d="M3.8 8.3A1.4 1.4 0 0 1 5.2 6.9h1.9L8 5.1h4l.9 1.8h1.9A1.4 1.4 0 0 1 16.2 8.3v6A1.4 1.4 0 0 1 14.8 15.7H5.2A1.4 1.4 0 0 1 3.8 14.3z"/><circle cx="10" cy="11" r="2.75"/>`,

  // State and instrument
  play: `<path d="M7.6 5.2 15.6 10 7.6 14.8Z"/>`,
  pause: `<path d="M7.8 5.2v9.6M12.2 5.2v9.6"/>`,
  stop: `<rect x="5.6" y="5.6" width="8.8" height="8.8" rx="1.4"/>`,
  step: `<path d="M6.4 5.4 13 10 6.4 14.6Z"/><path d="M15.2 5.4v9.2"/>`,
  crosshair: `<circle cx="10" cy="10" r="5.6"/><path d="M10 2.8v4.4M10 12.8v4.4M2.8 10h4.4M12.8 10h4.4"/>`,
  fullscreen: `<path d="M11.6 3.6h4.8v4.8M8.4 16.4H3.6v-4.8"/><path d="M16.4 3.6 11.2 8.8M3.6 16.4 8.8 11.2"/>`,
  compare: `<rect x="3.4" y="4.6" width="13.2" height="10.8" rx="1.6"/><path d="M10 4.6v10.8" stroke-width="1"/><path d="M5.2 7.6h3.4M5.2 10h2.6M5.2 12.4h3.4" stroke-width="1"/><path d="M11.4 7.6h3.4M11.4 10h3.4M11.4 12.4h1.8" stroke-width="1"/>`,
  filter: `<path d="M3.4 4.6h13.2L11.8 11v5.4L8.2 14.8V11z"/>`,
  search: `<circle cx="9" cy="9" r="5.4"/><path d="M12.82 12.82 16.9 16.9"/>`,
  loupe: `<circle cx="9" cy="9" r="5.6"/><path d="M12.96 12.96 17 17"/><rect x="6" y="6" width="6" height="6" stroke-width="1"/><path d="M9 6v6M6 9h6" stroke-width="1"/>`,
  layers: `<path d="M10 2.8 17.2 6.6 10 10.4 2.8 6.6z"/><path d="M2.8 10 10 13.8 17.2 10" stroke-width="1"/><path d="M2.8 13.4 10 17.2 17.2 13.4" stroke-width="1"/>`,
  lock: `<rect x="4.6" y="9" width="10.8" height="8" rx="1.6"/><path d="M7.2 9V6.6a2.8 2.8 0 0 1 5.6 0V9"/>`,
  unlock: `<rect x="4.6" y="9" width="10.8" height="8" rx="1.6"/><path d="M7.2 9V6.6a2.8 2.8 0 0 1 5.6 0"/>`,
  visible: `<path d="M2.6 10C4.6 6.6 7.1 5 10 5s5.4 1.6 7.4 5c-2 3.4-4.5 5-7.4 5s-5.4-1.6-7.4-5z"/><circle cx="10" cy="10" r="2.2"/>`,
  hidden: `<path d="M2.6 10C4.6 6.6 7.1 5 10 5s5.4 1.6 7.4 5c-2 3.4-4.5 5-7.4 5s-5.4-1.6-7.4-5z"/><circle cx="10" cy="10" r="2.2"/><path d="M4.2 15.8 15.8 4.2"/>`,
  pin: `<path d="M8.2 3.4v5.2l-2 2.6h7.6l-2-2.6V3.4z"/><path d="M7 3.4h6"/><path d="M10 11.2v5.4"/>`,
  link: `<path d="M8.6 11.4a3.4 3.4 0 0 1 0-4.8l2.2-2.2a3.4 3.4 0 0 1 4.8 4.8l-1.1 1.1"/><path d="M11.4 8.6a3.4 3.4 0 0 1 0 4.8l-2.2 2.2a3.4 3.4 0 0 1-4.8-4.8l1.1-1.1"/>`,
  collapse: `<path d="M14.16 4.05 10 7.8 5.84 4.05M5.84 15.95 10 12.2 14.16 15.95"/>`,
  expand: `<path d="M5.84 8.15 10 4.4 14.16 8.15M14.16 11.85 10 15.6 5.84 11.85"/>`,
  chevron: `<path d="M14.9 7.98 10 12.4 5.1 7.98"/>`,
  tune: `<path d="M3.4 6h13.2M3.4 10h13.2M3.4 14h13.2" stroke-width="1.25"/><circle cx="7" cy="6" r="1.8"/><circle cx="12.6" cy="10" r="1.8"/><circle cx="9" cy="14" r="1.8"/>`,
  grid: `<rect x="3.4" y="3.4" width="13.2" height="13.2" rx="1.4"/><path d="M7.8 3.4v13.2M12.2 3.4v13.2M3.4 7.8h13.2M3.4 12.2h13.2" stroke-width="1"/>`,
  snap: `<path d="M5.4 15.6V9.4a4.6 4.6 0 0 1 9.2 0v6.2h-3.2V9.4a1.4 1.4 0 0 0-2.8 0v6.2z"/><path d="M5.4 12.8h3.2M11.4 12.8h3.2" stroke-width="1"/>`,
  measure: `<rect x="2.6" y="7.4" width="14.8" height="5.2" rx="1.2"/><path d="M6 7.4v2.2M9.4 7.4v3M12.8 7.4v2.2" stroke-width="1"/>`,
  randomize: `<rect x="3.6" y="3.6" width="12.8" height="12.8" rx="2"/><circle cx="7.2" cy="7.2" r="1" fill="currentColor" stroke="none"/><circle cx="10" cy="10" r="1" fill="currentColor" stroke="none"/><circle cx="12.8" cy="12.8" r="1" fill="currentColor" stroke="none"/>`,
  refresh: `<path d="M4.27 12.09A6.1 6.1 0 0 1 14.67 6.08"/><path d="M14.67 3.38 14.67 6.08 12.01 5.61"/><path d="M15.73 7.91A6.1 6.1 0 0 1 5.33 13.92"/><path d="M5.33 16.62 5.33 13.92 7.99 14.39"/>`,
  info: `<circle cx="10" cy="10" r="7"/><path d="M10 9.4v4.4"/><path d="M10 6.5h0"/>`,
  warning: `<path d="M10 3.4 17.4 16.2H2.6z"/><path d="M10 8.4v3.4"/><path d="M10 14h0"/>`,
  error: `<circle cx="10" cy="10" r="7"/><path d="M7.6 7.6 12.4 12.4M12.4 7.6 7.6 12.4"/>`,
  busy: `<path d="M10 3.2A6.8 6.8 0 1 1 3.2 10"/>`,
  modeLight: `<circle cx="10" cy="10" r="3.5"/><path d="M15.3 10L17.7 10M13.75 6.25L15.44 4.56M10 4.7L10 2.3M6.25 6.25L4.56 4.56M4.7 10L2.3 10M6.25 13.75L4.56 15.44M10 15.3L10 17.7M13.75 13.75L15.44 15.44"/>`,
  modeDark: `<path d="M8.19 3.55A6.7 6.7 0 1 0 16.45 11.81A5.9 5.9 0 0 1 8.19 3.55Z"/>`,
  modeAuto: `<path d="M10 2.6Q10 10 17.4 10Q10 10 10 17.4Q10 10 2.6 10Q10 10 10 2.6Z"/>`,

  // Stroke cap, join, align and dash
  strokeWidth: `<path d="M3.4 5.6h13.2" stroke-width="1"/><path d="M3.4 10h13.2" stroke-width="2"/><path d="M3.4 15.2h13.2" stroke-width="3.4"/>`,
  strokeCap: `<path d="M2.5 10H12" stroke-linecap="butt"/><path d="M12 6V14" stroke-width="1"/>`,
  strokeJoin: `<path d="M4.4 15.5 10 5.5 15.6 15.5" stroke-linecap="butt" stroke-linejoin="miter"/>`,
  strokeAlign: `<circle cx="10" cy="10" r="6.2"/>`,
  capButt: `<path d="M5.5 5.25H14.5V14.75H5.5Z" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="miter"/>`,
  capRound: `<path d="M3.13 5.25H12.13V14.75H3.13Z" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="miter"/><path d="M12.13 4.5A5.5 5.5 0 0 1 12.13 15.5Z" fill="currentColor" stroke="none"/>`,
  capSquare: `<path d="M3.13 5.25H12.13V14.75H3.13Z" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="miter"/><path d="M12.13 4.5H17.63V15.5H12.13Z" fill="currentColor" stroke="none"/>`,
  joinMiter: `<path d="M10 3.5 15.6 15.5H4.4Z" fill="currentColor" stroke="none"/>`,
  joinRound: `<path d="M4.4 15.5V12a5.6 5.6 0 0 1 11.2 0v3.5Z" fill="currentColor" stroke="none"/>`,
  joinBevel: `<path d="M6.8 8.2h6.4l2.4 7.3H4.4Z" fill="currentColor" stroke="none"/>`,
  alignInner: `<path d="M10 3.8A6.2 6.2 0 1 0 10 16.2A6.2 6.2 0 1 0 10 3.8Z" fill="currentColor" stroke="none"/>`,
  alignCenter: `<path d="M10 2.1A7.9 7.9 0 1 0 10 17.9A7.9 7.9 0 1 0 10 2.1ZM10 5.5A4.5 4.5 0 1 0 10 14.5A4.5 4.5 0 1 0 10 5.5Z" fill="currentColor" stroke="none" fill-rule="evenodd"/>`,
  alignOuter: `<path d="M0 0H20V20H0ZM10 3.8A6.2 6.2 0 1 0 10 16.2A6.2 6.2 0 1 0 10 3.8Z" fill="currentColor" stroke="none" fill-rule="evenodd"/>`,
  dashSolid: `<path d="M2 10h16" stroke-width="3" stroke-linecap="butt"/>`,
  dashDashed: `<path d="M2 10h16" stroke-width="3" stroke-linecap="butt" stroke-dasharray="6 4"/>`,
  dashDotted: `<path d="M2 10h16" stroke-width="3" stroke-linecap="butt" stroke-dasharray="2.5 2"/>`,
  dashCustom: `<path d="M2 10h16" stroke-width="3" stroke-linecap="butt" stroke-dasharray="5 2 2 2"/>`,
  paintSolid: `<path d="M3.4 3.4H16.6V16.6H3.4Z" fill="currentColor" stroke="none" fill-opacity="1"/>`,
  paintLinear: `<path d="M3.4 3.4H6.7V16.6H3.4Z" fill="currentColor" stroke="none" fill-opacity="1"/><path d="M6.7 3.4H10V16.6H6.7Z" fill="currentColor" stroke="none" fill-opacity="0.68"/><path d="M10 3.4H13.3V16.6H10Z" fill="currentColor" stroke="none" fill-opacity="0.42"/><path d="M13.3 3.4H16.6V16.6H13.3Z" fill="currentColor" stroke="none" fill-opacity="0.2"/>`,
  paintRadial: `<path d="M3.4 3.4H16.6V16.6H3.4ZM4.95 4.95H15.05V15.05H4.95Z" fill="currentColor" fill-rule="evenodd" stroke="none" fill-opacity="0.7"/><path d="M4.95 4.95H15.05V15.05H4.95ZM6.5 6.5H13.5V13.5H6.5Z" fill="currentColor" fill-rule="evenodd" stroke="none" fill-opacity="0.53"/><path d="M6.5 6.5H13.5V13.5H6.5ZM8.05 8.05H11.95V11.95H8.05Z" fill="currentColor" fill-rule="evenodd" stroke="none" fill-opacity="0.37"/><path d="M8.05 8.05H11.95V11.95H8.05Z" fill="currentColor" fill-rule="evenodd" stroke="none" fill-opacity="0.2"/>`,
  paintConic: `<path d="M10 10L16.6 3.4L16.6 16.6Z" fill="currentColor" stroke="none" fill-opacity="1"/><path d="M10 10L16.6 16.6L3.4 16.6Z" fill="currentColor" stroke="none" fill-opacity="0.68"/><path d="M10 10L3.4 16.6L3.4 3.4Z" fill="currentColor" stroke="none" fill-opacity="0.42"/><path d="M10 10L3.4 3.4L16.6 3.4Z" fill="currentColor" stroke="none" fill-opacity="0.2"/>`,
  paintPattern: `<path d="M3.4 3.4L4.7 3.4L3.4 4.7Z" fill="currentColor" stroke="none"/><path d="M8.7 3.4L11.3 3.4L3.4 11.3L3.4 8.7Z" fill="currentColor" stroke="none"/><path d="M15.3 3.4L16.6 3.4L16.6 4.7L4.7 16.6L3.4 16.6L3.4 15.3Z" fill="currentColor" stroke="none"/><path d="M16.6 8.7L16.6 11.3L11.3 16.6L8.7 16.6Z" fill="currentColor" stroke="none"/><path d="M16.6 15.3L16.6 16.6L15.3 16.6Z" fill="currentColor" stroke="none"/><path d="M15.3 3.4L16.6 3.4L16.6 4.7Z" fill="currentColor" stroke="none"/><path d="M8.7 3.4L11.3 3.4L16.6 8.7L16.6 11.3Z" fill="currentColor" stroke="none"/><path d="M3.4 3.4L4.7 3.4L16.6 15.3L16.6 16.6L15.3 16.6L3.4 4.7Z" fill="currentColor" stroke="none"/><path d="M11.3 16.6L8.7 16.6L3.4 11.3L3.4 8.7Z" fill="currentColor" stroke="none"/><path d="M4.7 16.6L3.4 16.6L3.4 15.3Z" fill="currentColor" stroke="none"/>`,
  paintNone: `<path d="M3.4 3.4H16.6V16.6H3.4Z"/><path d="M3.4 16.6L16.6 3.4" stroke="var(--wzl-danger, #d94a3f)" stroke-width="1.8" stroke-linecap="butt"/>`,

  // Workspace layout
  layoutRows: `<rect x="3.4" y="3.4" width="13.2" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="3.4" y="8.3" width="13.2" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="3.4" y="13.2" width="13.2" height="3.4" rx="1" fill="currentColor" stroke="none"/>`,
  layoutColumns: `<rect x="3.4" y="3.4" width="3.4" height="13.2" rx="1" fill="currentColor" stroke="none"/><rect x="8.3" y="3.4" width="3.4" height="13.2" rx="1" fill="currentColor" stroke="none"/><rect x="13.2" y="3.4" width="3.4" height="13.2" rx="1" fill="currentColor" stroke="none"/>`,
  layoutGrid: `<rect x="3.4" y="3.4" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="8.3" y="3.4" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="13.2" y="3.4" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="3.4" y="8.3" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="8.3" y="8.3" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="13.2" y="8.3" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="3.4" y="13.2" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="8.3" y="13.2" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/><rect x="13.2" y="13.2" width="3.4" height="3.4" rx="1" fill="currentColor" stroke="none"/>`,

  // Arc profiles
  arcStraight: `<path d="M2.6 15H17.4"/>`,
  arcParabola: `<path d="M2.6 15Q10 -5 17.4 15"/>`,
  arcCircle: `<path d="M2.6 15A7.4 7.4 0 0 1 17.4 15"/>`,
  arcSine: `<path d="M2.6 10C3.83 7.38 5.07 5 6.3 5C7.53 5 8.77 7.38 10 10C11.23 12.62 12.47 15 13.7 15C14.93 15 16.17 12.62 17.4 10"/>`,
  arcBump: `<path d="M2.6 15C3.83 15 5.07 11.87 6.3 9.38C7.53 6.88 8.77 5 10 5C11.23 5 12.47 6.88 13.7 9.38C14.93 11.87 16.17 15 17.4 15"/>`,
  arcPlateau: `<path d="M2.6 15V8.6A3.6 3.6 0 0 1 6.2 5H13.8A3.6 3.6 0 0 1 17.4 8.6V15"/>`,
  arcBell: `<path d="M2.6 15C3.42 14.87 4.24 14.6 5.07 13.65C5.89 12.7 6.71 10.87 7.53 8.87C8.36 6.86 9.18 5 10 5C10.82 5 11.64 6.86 12.47 8.87C13.29 10.87 14.11 12.7 14.93 13.65C15.76 14.6 16.58 14.87 17.4 15"/>`,
  arcEllipse: `<path d="M2.6 15A7.4 10 0 0 1 17.4 15"/>`,
  arcLob: `<path d="M2.6 15C3.78 -0.6 10.74 4.2 17.4 15"/>`,
  arcDive: `<path d="M2.6 15C9.26 4.2 16.22 -0.6 17.4 15"/>`,
  arcTriangle: `<path d="M2.6 10L6.3 5L13.7 15L17.4 10"/>`,
  arcSquare: `<path d="M2.6 10L2.6 5L10 5L10 15L17.4 15L17.4 10"/>`,
  arcSawtooth: `<path d="M2.6 10L10 5L10 15L17.4 10"/>`,
  arcStair: `<path d="M2.6 10L4.97 10L4.97 5L8.82 5L8.82 10L11.18 10L11.18 15L15.03 15L15.03 10L17.4 10"/>`,
  arcZigzag: `<path d="M2.6 10L4.45 5L8.15 15L10 10L11.85 5L15.55 15L17.4 10"/>`,
  arcRipple: `<path d="M2.6 10C3.22 7.38 3.83 5 4.45 5C5.07 5 5.68 7.38 6.3 10C6.92 12.62 7.53 15 8.15 15C8.77 15 9.38 12.62 10 10C10.62 7.38 11.23 5 11.85 5C12.47 5 13.08 7.38 13.7 10C14.32 12.62 14.93 15 15.55 15C16.17 15 16.78 12.62 17.4 10"/>`,
  arcHop: `<path d="M2.6 15Q6.3 -5 10 15M10 15Q13.7 4 17.4 15"/>`,
  arcCusp: `<path d="M2.6 15Q7.34 12.8 10 5Q12.66 12.8 17.4 15"/>`,
} as const;

/** Every glyph name in the set. */
export type IconName = keyof typeof ICON_PATHS;

/** The region a glyph encloses, for `<Icon filled>`. A shape fills its own
 *  outline; a plotted curve fills down to the frame's baseline, reaching the outer
 *  edge of the stroke rather than stopping at the path's own endpoint. Only the
 *  glyphs where an enclosed region means something have an entry. */
export const ICON_FILLS = {
  arcStraight: `<path d="M1.85 15L2.6 15H17.4L18.15 15L18.15 15.75L1.85 15.75Z" fill="currentColor" stroke="none"/>`,
  arcParabola: `<path d="M2.31 15.69L2.6 15Q10 -5 17.4 15L17.69 15.69L17.69 15.75L2.31 15.75Z" fill="currentColor" stroke="none"/>`,
  arcCircle: `<path d="M2.52 15.75L2.6 15A7.4 7.4 0 0 1 17.4 15L17.48 15.75L17.48 15.75L2.52 15.75Z" fill="currentColor" stroke="none"/>`,
  arcSine: `<path d="M2.28 10.68L2.6 10C3.83 7.38 5.07 5 6.3 5C7.53 5 8.77 7.38 10 10C11.23 12.62 12.47 15 13.7 15C14.93 15 16.17 12.62 17.4 10L17.72 9.32L17.72 15.75L2.28 15.75Z" fill="currentColor" stroke="none"/>`,
  arcBump: `<path d="M1.87 15.18L2.6 15C3.83 15 5.07 11.87 6.3 9.38C7.53 6.88 8.77 5 10 5C11.23 5 12.47 6.88 13.7 9.38C14.93 11.87 16.17 15 17.4 15L18.13 15.18L18.13 15.75L1.87 15.75Z" fill="currentColor" stroke="none"/>`,
  arcPlateau: `<path d="M2.6 15.75L2.6 15V8.6A3.6 3.6 0 0 1 6.2 5H13.8A3.6 3.6 0 0 1 17.4 8.6V15L17.4 15.75L17.4 15.75L2.6 15.75Z" fill="currentColor" stroke="none"/>`,
  arcBell: `<path d="M1.86 15.13L2.6 15C3.42 14.87 4.24 14.6 5.07 13.65C5.89 12.7 6.71 10.87 7.53 8.87C8.36 6.86 9.18 5 10 5C10.82 5 11.64 6.86 12.47 8.87C13.29 10.87 14.11 12.7 14.93 13.65C15.76 14.6 16.58 14.87 17.4 15L18.14 15.13L18.14 15.75L1.86 15.75Z" fill="currentColor" stroke="none"/>`,
  arcEllipse: `<path d="M2.54 15.75L2.6 15A7.4 10 0 0 1 17.4 15L17.46 15.75L17.46 15.75L2.54 15.75Z" fill="currentColor" stroke="none"/>`,
  arcLob: `<path d="M2.5 15.74L2.6 15C3.78 -0.6 10.74 4.2 17.4 15L17.81 15.63L17.81 15.75L2.5 15.75Z" fill="currentColor" stroke="none"/>`,
  arcDive: `<path d="M2.19 15.63L2.6 15C9.26 4.2 16.22 -0.6 17.4 15L17.5 15.74L17.5 15.75L2.19 15.75Z" fill="currentColor" stroke="none"/>`,
  arcTriangle: `<path d="M2.15 10.6L2.6 10L6.3 5L13.7 15L17.4 10L17.85 9.4L17.85 15.75L2.15 15.75Z" fill="currentColor" stroke="none"/>`,
  arcSquare: `<path d="M2.6 10.75L2.6 10L2.6 5L10 5L10 15L17.4 15L17.4 10L17.4 9.25L17.4 15.75L2.6 15.75Z" fill="currentColor" stroke="none"/>`,
  arcSawtooth: `<path d="M1.98 10.42L2.6 10L10 5L10 15L17.4 10L18.02 9.58L18.02 15.75L1.98 15.75Z" fill="currentColor" stroke="none"/>`,
  arcStair: `<path d="M1.85 10L2.6 10L4.97 10L4.97 5L8.82 5L8.82 10L11.18 10L11.18 15L15.03 15L15.03 10L17.4 10L18.15 10L18.15 15.75L1.85 15.75Z" fill="currentColor" stroke="none"/>`,
  arcZigzag: `<path d="M2.34 10.7L2.6 10L4.45 5L8.15 15L10 10L11.85 5L15.55 15L17.4 10L17.66 9.3L17.66 15.75L2.34 15.75Z" fill="currentColor" stroke="none"/>`,
  arcRipple: `<path d="M2.43 10.73L2.6 10C3.22 7.38 3.83 5 4.45 5C5.07 5 5.68 7.38 6.3 10C6.92 12.62 7.53 15 8.15 15C8.77 15 9.38 12.62 10 10C10.62 7.38 11.23 5 11.85 5C12.47 5 13.08 7.38 13.7 10C14.32 12.62 14.93 15 15.55 15C16.17 15 16.78 12.62 17.4 10L17.57 9.27L17.57 15.75L2.43 15.75Z" fill="currentColor" stroke="none"/>`,
  arcHop: `<path d="M2.45 15.73L2.6 15Q6.3 -5 10 15L10.15 15.73L10.15 15.75L2.45 15.75ZM9.74 15.7L10 15Q13.7 4 17.4 15L17.66 15.7L17.66 15.75L9.74 15.75Z" fill="currentColor" stroke="none"/>`,
  arcCusp: `<path d="M1.94 15.35L2.6 15Q7.34 12.8 10 5Q12.66 12.8 17.4 15L18.06 15.35L18.06 15.75L1.94 15.75Z" fill="currentColor" stroke="none"/>`,
} as const;

/** The glyphs `<Icon filled>` can shade. */
export type FillableIconName = keyof typeof ICON_FILLS;
