// GENERATED by scripts/gen-cursors.mjs — do not edit by hand.
// Filled silhouettes on a 24-unit box; the halo is applied at bake time.

import type { CursorGlyph } from './types';

export const GLYPHS = {
  "pencil": {
    "box": 24,
    "hotspot": [
      5,
      19
    ],
    "paths": [
      {
        "role": "ink",
        "d": "M 5 19 L 7.5 16.5 L 16 8 L 19 11 L 10.5 19.5 L 8 19 Z"
      },
      {
        "role": "detail",
        "d": "M 14 6 L 19 11",
        "width": 1.2
      }
    ]
  },
  "pen": {
    "box": 24,
    "hotspot": [
      5,
      19
    ],
    "paths": [
      {
        "role": "ink",
        "d": "M 5 19 L 8.5 9.5 L 13 5 L 18 10 L 13.5 14.5 Z"
      },
      {
        "role": "detail",
        "d": "M 8.4 13.9 L 12.2 10.1",
        "width": 0.9
      }
    ]
  },
  "eyedropper": {
    "box": 24,
    "hotspot": [
      5,
      19
    ],
    "paths": [
      {
        "role": "ink",
        "d": "M 5 19 L 6.8 14.8 L 14.4 7.2 L 16.8 9.6 L 9.2 17.2 Z"
      },
      {
        "role": "ink",
        "d": "M 18.2 2.6 A 3.2 3.2 0 1 0 18.2 9 A 3.2 3.2 0 1 0 18.2 2.6 Z"
      }
    ]
  },
  "brush": {
    "box": 24,
    "hotspot": [
      12,
      12
    ],
    "radius": 9.9,
    "paths": [
      {
        "role": "stroke",
        "d": "M 12 2.1 A 9.9 9.9 0 1 0 12 21.9 A 9.9 9.9 0 1 0 12 2.1 Z",
        "width": 1.6
      }
    ]
  },
  "crosshairRect": {
    "box": 24,
    "hotspot": [
      9,
      9
    ],
    "paths": [
      {
        "role": "stroke",
        "d": "M 1.6 9 L 6.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 11.6 9 L 16.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 1.6 L 9 6.4",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 11.6 L 9 16.4",
        "width": 1.6
      },
      {
        "role": "ink",
        "d": "M 14.2 14.2 L 21 14.2 L 21 21 L 14.2 21 Z"
      }
    ]
  },
  "crosshairEllipse": {
    "box": 24,
    "hotspot": [
      9,
      9
    ],
    "paths": [
      {
        "role": "stroke",
        "d": "M 1.6 9 L 6.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 11.6 9 L 16.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 1.6 L 9 6.4",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 11.6 L 9 16.4",
        "width": 1.6
      },
      {
        "role": "ink",
        "d": "M 17.6 13.9 A 3.7 3.7 0 1 0 17.6 21.3 A 3.7 3.7 0 1 0 17.6 13.9 Z"
      }
    ]
  },
  "crosshairLine": {
    "box": 24,
    "hotspot": [
      9,
      9
    ],
    "paths": [
      {
        "role": "stroke",
        "d": "M 1.6 9 L 6.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 11.6 9 L 16.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 1.6 L 9 6.4",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 11.6 L 9 16.4",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 14.2 21 L 21 14.2",
        "width": 2.2
      }
    ]
  },
  "crosshairStar": {
    "box": 24,
    "hotspot": [
      9,
      9
    ],
    "paths": [
      {
        "role": "stroke",
        "d": "M 1.6 9 L 6.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 11.6 9 L 16.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 1.6 L 9 6.4",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 11.6 L 9 16.4",
        "width": 1.6
      },
      {
        "role": "ink",
        "d": "M 17.6 13.4 L 18.72 16.06 L 21.59 16.3 L 19.41 18.19 L 20.07 21 L 17.6 19.5 L 15.13 21 L 15.79 18.19 L 13.61 16.3 L 16.48 16.06 Z"
      }
    ]
  },
  "crosshairPolygon": {
    "box": 24,
    "hotspot": [
      9,
      9
    ],
    "paths": [
      {
        "role": "stroke",
        "d": "M 1.6 9 L 6.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 11.6 9 L 16.4 9",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 1.6 L 9 6.4",
        "width": 1.6
      },
      {
        "role": "stroke",
        "d": "M 9 11.6 L 9 16.4",
        "width": 1.6
      },
      {
        "role": "ink",
        "d": "M 17.6 13.5 L 21.5 16.33 L 20.01 20.92 L 15.19 20.92 L 13.7 16.33 Z"
      }
    ]
  },
  "resize": {
    "box": 24,
    "hotspot": [
      12,
      12
    ],
    "paths": [
      {
        "role": "ink",
        "d": "M 2.5 12 L 7 8.8 L 7 10.7 L 17 10.7 L 17 8.8 L 21.5 12 L 17 15.2 L 17 13.3 L 7 13.3 L 7 15.2 Z"
      }
    ]
  },
  "rotate": {
    "box": 24,
    "hotspot": [
      12,
      12
    ],
    "paths": [
      {
        "role": "stroke",
        "d": "M 5.8 9.74 A 6.6 6.6 0 0 1 18.2 9.74",
        "width": 2.8
      },
      {
        "role": "ink",
        "d": "M 4.22 14.07 L 2.98 8.72 L 8.62 10.77 Z"
      },
      {
        "role": "ink",
        "d": "M 19.78 14.07 L 15.38 10.77 L 21.02 8.72 Z"
      }
    ]
  }
} as const satisfies Record<string, CursorGlyph>;

/** Every glyph name in the set. */
export type CursorGlyphName = keyof typeof GLYPHS;
