export {
  parseRoute,
  formatRoute,
  formatPhaseAtom,
  collapseShiftPairs,
  describeRoute,
  describeRouteParts,
  ROUTE_TERMS,
  ROUTE_FIELD_DEFINITIONS,
  RESERVED_SIGILS,
  ACTIVE_SIGILS,
  RESERVED_ID_PREFIXES,
  RESERVED_ID_NAMES,
  VALID_MOD_NAMES,
  MOD_NAME_SET,
  canonicalModifiers,
} from '@weasel-js/gestures';
export type {
  ParsedRoute,
  ParsedModifiers,
  ModifierKey,
  ModRequirement,
  PhaseAtom,
  ChannelRef,
  DescribeRouteOptions,
  RouteDescriptionPart,
  RouteTermLabel,
  RouteFieldName,
} from '@weasel-js/gestures';
