export type {
  GestureSpec,
  KeySpec,
  KeyHeldSpec,
  WheelSpec,
  PinchSpec,
  ClickSpec,
  DragSpec,
  MultiTouchSpec,
  ContextMenuSpec,
  MultiTouchTapSpec,
  DropSpec,
  PasteSpec,
  ModSpec,
  TargetSpec,
  PhaseSpec,
} from '@weasel-js/gestures';
