// GENERATED by apps/theme-editor/scripts/gen-brand-colors.mjs
// Source: https://brickset.com/colours/status-Current

/** One LEGO colour: Brickset's name and the value it publishes. */
export interface LegoColor {
  readonly name: string;
  readonly hex: string;
}

/**
 * LEGO colours currently in production, solid and opaque, neutrals excluded.
 *
 * Brickset is the source because it carries the one field LDraw's LDConfig
 * does not: production status. LDConfig would put Fabuland Orange and Maersk
 * Blue in here beside Coral and Dark Azure with nothing to tell them apart.
 */
export const LEGO_COLORS: readonly LegoColor[] = [
  { name: "Blue Violet", hex: '#806aec' },
  { name: "Brick Yellow", hex: '#b0a06f' },
  { name: "Bright Blue", hex: '#1e5aa8' },
  { name: "Bright Bluish Green", hex: '#069d9f' },
  { name: "Bright Green", hex: '#58ab41' },
  { name: "Bright Orange", hex: '#d67923' },
  { name: "Bright Purple", hex: '#d3359d' },
  { name: "Bright Red", hex: '#b40000' },
  { name: "Bright Reddish Violet", hex: '#901f76' },
  { name: "Bright Yellow", hex: '#fac80a' },
  { name: "Bright Yellowish Green", hex: '#a5ca18' },
  { name: "Cool Yellow", hex: '#ffec6c' },
  { name: "Dark Azur", hex: '#469bc3' },
  { name: "Dark Brown", hex: '#372100' },
  { name: "Dark Green", hex: '#00852b' },
  { name: "Dark Orange", hex: '#91501c' },
  { name: "Earth Blue", hex: '#19325a' },
  { name: "Earth Green", hex: '#00451a' },
  { name: "Flame Yellowish Orange", hex: '#fcac00' },
  { name: "Lavender", hex: '#cda4de' },
  { name: "Light Nougat", hex: '#ffc995' },
  { name: "Light Purple", hex: '#ff9ecd' },
  { name: "Light Royal Blue", hex: '#9dc3f7' },
  { name: "Medium Azur", hex: '#68c3e2' },
  { name: "Medium Blue", hex: '#7396c8' },
  { name: "Medium Brown", hex: '#755945' },
  { name: "Medium Lavender", hex: '#a06eb9' },
  { name: "Medium Lilac", hex: '#441a91' },
  { name: "Medium Nougat", hex: '#aa7d55' },
  { name: "Nougat", hex: '#bb805a' },
  { name: "Olive Green", hex: '#77774e' },
  { name: "Reddish Brown", hex: '#5f3109' },
  { name: "Reddish Orange", hex: '#ca4c0b' },
  { name: "Sand Blue", hex: '#70819a' },
  { name: "Sand Green", hex: '#708e7c' },
  { name: "Sand Yellow", hex: '#897d62' },
  { name: "Sienna Brown", hex: '#915c3c' },
  { name: "Spring Yellowish Green", hex: '#e2f99a' },
];
