import { PANEL_SLOTS, PANEL_STANCES, type PanelSlot } from '@weasel-js/theme';

/** Build-time only: `npm run gen:panel-stances` writes this into Properties.module.css. */

export const BEGIN = '/* BEGIN GENERATED by `npm run gen:panel-stances` — do not edit. */';
export const END = '/* END GENERATED panel stances */';

const local = (slot: PanelSlot) => `--_p-${slot.name}`;

/** `var(--wzl-panel-<name>, <fallback>)`. */
const slotVar = (name: string, fallback?: string) =>
  `var(${`--wzl-panel-${name}`}${fallback === undefined ? '' : `, ${fallback}`})`;

/** What an unstanced panel reads for `slot`. */
function base(slot: PanelSlot): string {
  // Density outranks the theme's pad; a stance's pad outranks both, so
  // `preview` can sit its content on the edge.
  if (slot.name === 'pad') return `var(--wzl-prop-panel-pad, ${slotVar('pad')})`;
  if (slot.name === 'tone') return slotVar('tone', 'var(--_p-surface)');
  if (slot.name === 'accent') return slotVar('tone');
  return slotVar(slot.name);
}

/** What a panel with `stance` reads for `slot` — nested, when `nested`. */
function stanced(stance: string, slot: PanelSlot, nested: boolean): string {
  if (slot.name === 'tone') {
    const own = slotVar(`${stance}-tone`, 'var(--_p-surface)');
    return slotVar('tone', nested ? slotVar(`${stance}-nested-tone`, own) : own);
  }
  const outer = slotVar(`${stance}-${slot.name}`, slot.stanced ?? base(slot));
  return nested ? slotVar(`${stance}-nested-${slot.name}`, outer) : outer;
}

export function panelStanceCss(): string {
  const block = (selector: string, decl: (slot: PanelSlot) => string) =>
    `${selector} {\n${PANEL_SLOTS.map((slot) => `  ${local(slot)}: ${decl(slot)};`).join('\n')}\n}`;
  return [
    BEGIN,
    block('.panel', base),
    ...PANEL_STANCES.flatMap((stance) => [
      block(`.panel[data-stance='${stance}']`, (slot) => stanced(stance, slot, false)),
      block(`.panel[data-stance='${stance}'][data-nested]`, (slot) => stanced(stance, slot, true)),
    ]),
    END,
  ].join('\n\n');
}

/** `css` with its generated region replaced by a fresh one. */
export function withPanelStanceCss(css: string): string {
  const start = css.indexOf(BEGIN);
  const stop = css.indexOf(END);
  if (start === -1 || stop === -1) throw new Error('Properties.module.css has no generated panel-stance region');
  return css.slice(0, start) + panelStanceCss() + css.slice(stop + END.length);
}
