#!/usr/bin/env node
/**
 * Turn a vitest benchmark JSON report into the committed Markdown baseline.
 *
 * Usage:
 *   node scripts/bench-report.mjs [--in <json>] [--out <md>]
 *
 * Defaults read `tests/bench/results/baseline.json` and write
 * `tests/bench/results/BASELINE.md`. Prints one line per benchmark as it
 * goes, so the step is legible in a terminal rather than silent.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import os from 'node:os';

const args = process.argv.slice(2);
const argOf = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
};

const repoRoot = resolve(import.meta.dirname, '..');
const inPath = resolve(repoRoot, argOf('--in', 'tests/bench/results/baseline.json'));
const outPath = resolve(repoRoot, argOf('--out', 'tests/bench/results/BASELINE.md'));

const report = JSON.parse(readFileSync(inPath, 'utf8'));

/** ms, rendered at a precision that stays readable across six orders of magnitude. */
function ms(v) {
  if (v >= 100) return v.toFixed(0);
  if (v >= 1) return v.toFixed(2);
  if (v >= 0.01) return v.toFixed(4);
  return v.toExponential(2);
}

const rows = [];
let total = 0;
for (const file of report.files) for (const g of file.groups) total += g.benchmarks.length;

let i = 0;
for (const file of report.files) {
  const suite = relative(repoRoot, file.filepath);
  for (const group of file.groups) {
    // `fullName` is prefixed with the file path, which the `## suite` heading
    // already carries.
    const groupName = group.fullName.replace(/^.*?\.bench\.ts > /, '');
    for (const b of group.benchmarks) {
      i++;
      console.log(
        `[${i}/${total}] ${suite} > ${groupName} :: ${b.name}  median=${ms(b.median)}ms  rme=±${b.rme.toFixed(1)}%`,
      );
      rows.push({ suite, group: groupName, ...b });
    }
  }
}

const lines = [];
lines.push('# Benchmark baseline');
lines.push('');
lines.push(
  'Generated by `npm run bench:baseline`. **These are one machine\'s numbers, ' +
  'not a threshold.** They are portable as ratios and curve shapes, not as ' +
  'absolute milliseconds. See `tests/bench/README.md`.',
);
lines.push('');
lines.push('| | |');
lines.push('|---|---|');
lines.push(`| Measured | ${new Date().toISOString().slice(0, 10)} |`);
lines.push(`| CPU | ${os.cpus()[0]?.model ?? 'unknown'} (${os.cpus().length} threads) |`);
lines.push(`| Arch | ${process.platform}/${process.arch} |`);
lines.push(`| Node | ${process.version} |`);
lines.push(`| Memory | ${Math.round(os.totalmem() / 1024 ** 3)} GB |`);
lines.push('');
lines.push(
  '`median` is the number to compare — the mutating and allocation-heavy ' +
  'benchmarks take periodic GC pauses that inflate the mean by an order of ' +
  'magnitude without the code having changed. `rme` is the relative margin ' +
  'of error on the mean; a large one means read the median and ignore the ' +
  'mean entirely.',
);
lines.push('');

let currentSuite = null;
let currentGroup = null;
for (let n = 0; n < rows.length; n++) {
  const r = rows[n];
  if (r.suite !== currentSuite) {
    currentSuite = r.suite;
    currentGroup = null;
    lines.push(`## ${r.suite}`);
    lines.push('');
  }
  if (r.group !== currentGroup) {
    currentGroup = r.group;
    lines.push(`### ${r.group}`);
    lines.push('');
    lines.push('| benchmark | median (ms) | min (ms) | ops/sec | rme | samples |');
    lines.push('|---|---:|---:|---:|---:|---:|');
  }
  lines.push(
    `| ${r.name} | ${ms(r.median)} | ${ms(r.min)} | ` +
    `${Math.round(r.hz).toLocaleString('en-US')} | ±${r.rme.toFixed(1)}% | ${r.sampleCount} |`,
  );
  if (rows[n + 1]?.group !== r.group) lines.push('');
}

writeFileSync(outPath, `${lines.join('\n')}\n`);
console.log(`\nWrote ${relative(repoRoot, outPath)} (${rows.length} benchmarks).`);
