/**
 * Generates every token artifact from the DTCG source. Run via
 * `npm run gen:tokens -w @weasel-js/theme`; CI re-runs it and fails on a diff,
 * so the committed output under src/generated/ is never edited by hand.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { flattenTokens } from '../src/dtcg/flatten';
import { resolveTokens, mergeTokens } from '../src/dtcg/resolve';
import type { FlatTokens } from '../src/dtcg/types';

const here = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = resolve(here, '../tokens');
// Overridable so the determinism check can generate into a temp dir instead of
// rewriting the committed files other tests are reading from concurrently.
const OUT_DIR = process.env.WZL_TOKENS_OUT_DIR
  ? resolve(process.env.WZL_TOKENS_OUT_DIR)
  : resolve(here, '../src/generated');

const readJson = (p: string) => JSON.parse(readFileSync(p, 'utf8'));

interface ThemeManifest {
  name: string;
  defaultMode: string;
  modes: Record<string, { colorScheme: 'dark' | 'light' }>;
}

interface LoadedTheme {
  manifest: ThemeManifest;
  primitives: FlatTokens;
  modes: Record<string, FlatTokens>;
}

/** `{color.gray-100}` → `var(--wzl-gray-100)`; literals pass through. */
function cssValue(name: string, tokens: FlatTokens): string {
  const token = tokens[name];
  const raw = token.value;
  const isRef = typeof raw === 'string' && /^\{[^}]+\}$/.test(raw.trim());

  if (isRef) {
    const path = (raw as string).trim().slice(1, -1);
    const dot = path.indexOf('.');
    const target = dot === -1 ? path : path.slice(dot + 1);
    if (token.alpha !== undefined) {
      const pct = Math.round(token.alpha * 100);
      return `color-mix(in srgb, var(--wzl-${target}) ${pct}%, transparent)`;
    }
    return `var(--wzl-${target})`;
  }

  // Non-ref with alpha would be an authoring error; resolveTokens catches it.
  return resolveTokens({ [name]: token })[name];
}

function loadTheme(dir: string): LoadedTheme {
  const manifest: ThemeManifest = readJson(resolve(dir, 'theme.json'));
  const primitives = flattenTokens(readJson(resolve(dir, 'primitives.tokens.json')));
  const modes: Record<string, FlatTokens> = {};
  for (const mode of Object.keys(manifest.modes)) {
    modes[mode] = flattenTokens(readJson(resolve(dir, 'modes', `${mode}.tokens.json`)));
  }
  return { manifest, primitives, modes };
}

function emitCss(themes: LoadedTheme[]): string {
  const lines: string[] = [
    '/* GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    ' * Source: packages/theme/tokens/<theme>/',
    ' */',
    '',
  ];

  for (const { manifest, primitives, modes } of themes) {
    const defaults = mergeTokens(primitives, modes[manifest.defaultMode]);

    lines.push(':root {');
    // The default mode's scheme, not just its token values: without it a
    // surface that never calls `applyTheme` gets dark colors and light native
    // widgets — a range track and a scrollbar painted for the wrong theme.
    lines.push(`  color-scheme: ${manifest.modes[manifest.defaultMode].colorScheme};`);
    for (const name of Object.keys(defaults)) {
      const desc = defaults[name].description;
      if (desc) lines.push(`  /* ${desc} */`);
      lines.push(`  --wzl-${name}: ${cssValue(name, defaults)};`);
    }
    lines.push('}', '');

    lines.push(':root {');
    lines.push('  font-family: var(--wzl-font-ui);');
    lines.push('  font-weight: var(--wzl-font-weight-normal);');
    lines.push('}', '');

    for (const [mode, cfg] of Object.entries(manifest.modes)) {
      const merged = mergeTokens(primitives, modes[mode]);
      lines.push(`[data-wzl-theme='${manifest.name}'][data-wzl-mode='${mode}'],`);
      lines.push(`[data-wzl-mode='${mode}'] {`);
      lines.push(`  color-scheme: ${cfg.colorScheme};`);
      for (const name of Object.keys(modes[mode])) {
        lines.push(`  --wzl-${name}: ${cssValue(name, merged)};`);
      }
      lines.push('}', '');
    }
  }

  return lines.join('\n');
}

function emitThemes(themes: LoadedTheme[]): string {
  const entries = themes.map(({ manifest, primitives, modes }) => {
    const modeEntries = Object.keys(manifest.modes).map((mode) => {
      const resolved = resolveTokens(mergeTokens(primitives, modes[mode]));
      const body = Object.entries(resolved)
        .map(([n, v]) => `      '--wzl-${n}': ${JSON.stringify(v)},`)
        .join('\n');
      return `    ${JSON.stringify(mode)}: {\n${body}\n    },`;
    });
    return [
      `  ${JSON.stringify(manifest.name)}: {`,
      `    name: ${JSON.stringify(manifest.name)},`,
      `    defaultMode: ${JSON.stringify(manifest.defaultMode)},`,
      '    modes: {',
      modeEntries.join('\n'),
      '    },',
      '  },',
    ].join('\n');
  });

  const names = themes
    .flatMap(({ manifest, primitives, modes }) =>
      Object.keys(mergeTokens(primitives, modes[manifest.defaultMode])),
    )
    .map((n) => `  | '--wzl-${n}'`);

  const sources = Object.fromEntries(
    themes.map(({ manifest, primitives, modes }) => [manifest.name, { primitives, modes }]),
  );

  return [
    '// GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    '',
    "import type { RawToken } from '../dtcg/types';",
    '',
    '/** Every design token the built-in themes declare, spelled as the CSS',
    ' *  custom property it becomes. */',
    'export type TokenName =',
    `${[...new Set(names)].sort().join('\n')};`,
    '',
    '/** A built-in theme with its aliases already collapsed: every mode maps',
    ' *  every token name to a final CSS value. */',
    'export interface GeneratedTheme {',
    '  readonly name: string;',
    '  readonly defaultMode: string;',
    '  readonly modes: Readonly<Record<string, Readonly<Record<TokenName, string>>>>;',
    '}',
    '',
    '/** The built-in themes, resolved, keyed by theme name. Read this to list',
    ' *  or preview themes without resolving a token graph yourself. */',
    'export const THEMES = {',
    entries.join('\n'),
    '} as const satisfies Record<string, GeneratedTheme>;',
    '',
    '/** Unresolved token graph. `extends` needs the aliases intact so an override',
    ' *  of a base primitive still reaches everything referencing it. */',
    'export interface ThemeSource {',
    '  readonly primitives: Readonly<Record<string, RawToken>>;',
    '  readonly modes: Readonly<Record<string, Readonly<Record<string, RawToken>>>>;',
    '}',
    '',
    '/** The same built-in themes as `THEMES`, unresolved. This is what',
    ' *  `defineTheme` layers onto. */',
    `export const THEME_SOURCES: Readonly<Record<string, ThemeSource>> = ${JSON.stringify(sources, null, 2)};`,
    '',
  ].join('\n');
}

function emitManifest(themes: LoadedTheme[]): string {
  const { manifest, primitives, modes } = themes[0];
  const all = mergeTokens(primitives, modes[manifest.defaultMode]);
  const resolved = resolveTokens(all);

  const rows = Object.entries(all).map(([name, token]) => {
    const group = name.includes('-') ? name.slice(0, name.indexOf('-')) : name;
    return `  { name: '--wzl-${name}', type: ${JSON.stringify(token.type)}, group: ${JSON.stringify(group)}, defaultValue: ${JSON.stringify(resolved[name])}, description: ${JSON.stringify(token.description ?? '')} },`;
  });

  return [
    '// GENERATED by packages/theme/scripts/build-tokens.ts — do not edit.',
    '',
    '/** One row of `TOKEN_MANIFEST`: a token, its DTCG type, the name-prefix',
    ' *  group it belongs to, its value in the default theme and mode, and the',
    ' *  description it was authored with (empty string if none). */',
    'export interface TokenManifestEntry {',
    '  readonly name: string;',
    '  readonly type: string;',
    '  readonly group: string;',
    '  readonly defaultValue: string;',
    '  readonly description: string;',
    '}',
    '',
    '/** Every token of the default theme in its default mode, described. Meant',
    ' *  for tooling that presents the token set — docs pages, token browsers,',
    ' *  the Storybook CSS-vars addon — not for resolving values at runtime. */',
    'export const TOKEN_MANIFEST: readonly TokenManifestEntry[] = [',
    rows.join('\n'),
    '];',
    '',
  ].join('\n');
}

const themeDirs = readdirSync(TOKENS_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => resolve(TOKENS_DIR, d.name))
  .sort((a, b) => basename(a).localeCompare(basename(b)));

const themes = themeDirs.map(loadTheme);

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(resolve(OUT_DIR, 'tokens.css'), emitCss(themes));
writeFileSync(resolve(OUT_DIR, 'themes.ts'), emitThemes(themes));
writeFileSync(resolve(OUT_DIR, 'manifest.ts'), emitManifest(themes));

console.log(`Generated ${themes.length} theme(s) → ${OUT_DIR}`);
