// GENERATED by packages/ui/scripts/gen-icons.mjs — do not edit by hand.
// Drawn in packages/ui/scripts/icons/; @weasel-js/ui's ICON_PATHS points here.

/**
 * @experimental
 * SVG bodies of the glyphs the undo, redo and delete actions ship as their
 * icons: 20x20 viewBox, stroked in currentColor at stroke-width 1.5 with round
 * caps and joins. `<Icon name="undo" />` in `@weasel-js/ui` draws the same one.
 */
export const ACTION_GLYPHS = {
  delete: `<path d="M3.6 5.8h12.8M8 5.8V4.5A1.1 1.1 0 0 1 9.1 3.4h1.8A1.1 1.1 0 0 1 12 4.5v1.3"/><path d="M5.2 5.8v9.6A1.6 1.6 0 0 0 6.8 17h6.4a1.6 1.6 0 0 0 1.6-1.6V5.8"/><path d="M8.4 8.8v5.2M11.6 8.8v5.2" stroke-width="1"/>`,
  undo: `<path d="M4.4 8.4h6.8a3.6 3.6 0 0 1 0 7.2H8.6"/><path d="M6.47 10.14 4.4 8.4 6.47 6.66"/>`,
  redo: `<path d="M15.6 8.4H8.8a3.6 3.6 0 0 0 0 7.2H11.4"/><path d="M13.53 6.66 15.6 8.4 13.53 10.14"/>`,
} as const;
